#pragma once

#define	AMBUSH_ENEMY_COUNT  4
#define	HINT_MOVIE_COUNT	70
// in reality there are 64 hint movies, not 70.
// 70 is just the constant

enum STAGE_ENUM {
    STAGE_1,
    STAGE_2,
    STAGE_3,
    STAGE_4,
    STAGE_5,
    STAGE_6,
    STAGE_7,
    STAGE_8,
    STAGE_9,
    STAGE_COIN_BATTLE = 19,
    STAGE_GHOST_HOUSE,
    STAGE_TOWER,
    STAGE_TOWER_2,
    STAGE_CASTLE,
    STAGE_CASTLE_2,
    STAGE_KINOKO_HOUSE,
    STAGE_KINOKO_HOUSE_2,
    STAGE_KINOKO_HOUSE_3,
    STAGE_KINOKO_HOUSE_4,
    STAGE_ENEMY = 32,
    STAGE_ENEMY_2,
    STAGE_ENEMY_3,
    STAGE_CANNON,
    STAGE_DOOMSHIP = 37,
    STAGE_RESCUE,
    STAGE_TITLE,
    STAGE_PEACH_CASTLE,
    STAGE_STAFFROLL,
    STAGE_COUNT
};

enum WORLD_ENUM {
    WORLD_1,
    WORLD_2,
    WORLD_3,
    WORLD_4,
    WORLD_5,
    WORLD_6,
    WORLD_7,
    WORLD_8,
    WORLD_9,
    WORLD_10,
    WORLD_COUNT,

    LAST_WORLD = WORLD_8,
    NORMAL_WORLD_COUNT = LAST_WORLD + 1,
    SPECIAL_WORLD_COUNT = WORLD_COUNT - NORMAL_WORLD_COUNT - 1
};

enum COURSE_COMPLETION_ENUM {
    COIN1_COLLECTED = 0x1,
    COIN2_COLLECTED = 0x2,
    COIN3_COLLECTED = 0x4,
    COIN_MASK = COIN1_COLLECTED | COIN2_COLLECTED | COIN3_COLLECTED,
    GOAL_NORMAL = 0x10,
    GOAL_SECRET = 0x20,
    GOAL_MASK = GOAL_NORMAL | GOAL_SECRET,
    SUPER_GUIDE_GOAL_NORMAL = 0x80,
    SUPER_GUIDE_GOAL_SECRET = 0x100,
    SUPER_GUIDE_GOAL_MASK = SUPER_GUIDE_GOAL_NORMAL | SUPER_GUIDE_GOAL_SECRET
};

enum WORLD_COMPLETION_ENUM {
    WORLD_UNLOCKED = 0x1
};

enum GAME_COMPLETION_ENUM {
    SAVE_EMPTY = 0x1,
    FINAL_BOSS_BEATEN = 0x2,
    GOAL_ALL = 0x4,
    COIN_ALL = 0x8,
    COIN_ALL_SPECIAL = 0x10,
    GAME_COMPLETED = 0x20,
    SUPER_GUIDE_TRIGGERED = 0x40
};

enum START_KINOKO_KIND_ENUM {
    NONE,
    YELLOW,
    RED,
    GREEN,
    YELLOW_RESCUE,
    RED_RESCUE,
    GREEN_RESCUE
};

enum PLAYER_CHARACTER_ENUM {
    MARIO,
    LUIGI,
    BLUE_TOAD,
    YELLOW_TOAD,
    PLAYER_COUNT
};

enum PLAYER_POWERUP_ENUM {
    NO_POWERUP,
    MUSHROOM,
    FIRE_FLOWER,
    MINI_MUSHROOM,
    PROPELLER_SHROOM,
    PENGUIN_SUIT,
    ICE_FLOWER,
    POWERUP_COUNT
};


enum PLAYER_CREATE_ITEM_ENUM {
    NO_CREATE_ITEM = 0x0,
    STAR_POWER = 0x1,
    RIDING_YOSHI = 0x2,
    BUBBLED = 0x4,
    RESCUE_TOAD = 0x8
};
