#pragma once
#include <QMessageBox>
#include <QListWidgetItem>
#include <QFile>
#include <QFileDialog>
#include <QStringList>
#include <QDataStream>
#include <QSpinBox>
#include <QComboBox>
#include <QListWidget>
#include <QCloseEvent>
#include <QStatusBar>